environment_name       = "prod"
environment_project_id = "rueth-altostrat-prod-417913"
github_email           = "arueth@gmail.com"
github_org             = "rueth-io"
github_user            = "arueth"
